In [27]:
import torch
x=torch.ones(2,2,requires_grad=True)
print(x,x.grad_fn)
y=x+2
print(y,y.grad_fn)
z=torch.normal(torch.tensor([0.0,0]),torch.tensor([1.0,1]))
z


tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x0000018E55597B80>


tensor([0.7319, 0.6983])

In [5]:
import torch
x=torch.ones(2,2,requires_grad=True)
print(x,x.grad_fn)
y=x+2
print(y,y.grad_fn)
print(x.is_leaf,y.is_leaf)
z=y*y*3
print(z)
out=z.mean()

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x000001A5AB6A6A90>
True False
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
